{% set name = "morepath" %}
{% set version = "0.19" %}
{% set sha256 = "3d3f075083766e7d9c1bd184bf927590e862caa8a385f9a8a572422c0d69606a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.4
    - pip

  run:
    - python >=3.4
    - webob >=1.7.0
    - reg >=0.12
    - dectate >=0.14
    - importscan >= 0.2

test:
  imports:
    - morepath

about:
  home: http://morepath.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A micro web-framework with superpowers'
  description: |
    Morepath is a Python web framework. An application consists of models. Each
    type of model is published on a URL path. Content is exposed to the web
    using views.
  doc_url: http://morepath.readthedocs.io/
  dev_url: https://github.com/morepath/morepath
  
extra:
  recipe-maintainers:
    - stuertz
