travis:
  secure:
    BINSTAR_TOKEN: E8JZl30rOny2n55lFULiskhyi3/ta9GH7P3tkr8ERsvNK0tWCSKw6gpwe729snntJ3EC9hlaj0HeRTYNY00u/Noz3cZBw0odM+Dc8xDPxXW6749uX07lmmS/sZAXMCheGdUbRW/YR2vVWRN7D5dIME6fe76KtlT5I5TUiy3rmkkVdKPBw+u+7ROWLUo/HgjnHx8qTzxfYcpg+OfovjO9ptPnBKkzcLbc33sF9Q3F0Opjv+RnjT3knkC+l8LfXYScX94WmpNH0UgpuPTJYHOyWlKH4Tr9pXlGDOWh5IteertBDI409BSFYqZ9MwapEw6fcEOGmrOL02DrGvuIl/rQJpN1FTSD7ICy4grtkyb5+eZkqrrHJNRaxtscZIvGT2aDZrCKZTGN1vNNYslBISTbF9UMRbBzGEUOLO8WptBUph6/uUu7wjSNqta3VhAkOPPICJrFuYe4dKvlFIuaj5XuzMolKDgTauAd5cXnVjghFhRF0ztUU4TIQXqYZ68FxyS9QoBtEpqsSVOywbraBBoDMa6lOCSsomLW5wOTCkripg84qRBvHLorS4IONA7ATyp5p7dFuiUSC0TuVtv4CZrmtE5EvhA8p0T2kAiejVsl4kNkqBYM9bfmoVtTYb2Z3M7zHoFbxogM7vzMHTeTM6CNHDpntKEicBF9axW1GSy4M5c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
