travis:
  secure:
    BINSTAR_TOKEN: Mx6amhy39+ll1MX7FMavUuo+cerVAzGZhVEFSpe1xRSHASt4ZySBynkJcwMuw14EqopYRgYEZbiTY2RhFomFA9dh4mZGljVVAJtWbRHw9A7tAzyKexX48YjV2wS7gRn7IY6m+oq4nR60ej1m3Ajk37O//FA5kMq0UrQwaTrOTyDeUVwARUe3GDpjYGURfV1opSdaReKYvIbULzaj9tByvTVgdClQW4C3kYXN38mB7vt7Zjh4bFCLSHnaO2UxasmI5klku8y/Zi+uA0N6pGiEAZzkcQhC4ln25XpO7KNasB1Fy5B1fan6QXb3yY5Va3GDlrRV2Ii+bXtzM6tkYsM7zR3eyamF793q7DHnsBe0QGwd4jtlf3Qdxy3Jz0c4rnZZ2NSr7tAx1hka7scFhHCq6eHP6zaTuarVrgHKo11Cm+FcYeZ2q8To5Ecsk/97p/sISKWZoruLEGsmKzPMpzWuppajNCBNcoOhMrAxPN6GtVkvSDRPZ693gS4C+/4eQ302tkchV0OlH2SW4wUm2G940LKM9zkLYWzF6VRYqX6g6Qkt5CQ8VxIwYfMMSme3ggxDG1JEbA8uGpWdmZ25b4YNLeVcYIjOjKYmqhX/SCYNKyX5nWtupHrlLWyH8r4O/Vjn/Zgv2IsBh74QJaLLyJkhjNbmvnUBPsyKbv0aYHcB3fs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
